### ISSUE TITLE
Template inputs

### ISSUE THREAD

**Issue by colebemis** [lumen-notes/lumen#117]
## Types

```ts
type TemplateInput = { 
  type: 'string' | 'number' | 'boolean' | 'choice' // Start with just 'string' for now
  required?: boolean
  default?: any
  description?: string
}

type Template = {
  name: string
  inputs: Record<string, TemplateInput>
}

```

## Example

```
---
template:
  name: 'Book'
  inputs:
    isbn:
      type: string
      description: ISBN-13
---
```
